In [1]:
import pandas as pd

import matplotlib as plt

In [2]:
path="Resources/googletrends.csv"

data = pd.read_csv(path) 

data.columns=['Date','CERB','Mask','Bike','Zoom', 'Patio']
data=data.drop(data.index[[0,1]])
data=data.reset_index()
data.head()

   index        Date CERB Mask Bike Zoom Patio
0      2  2020-01-01   <1    5    7    1     1
1      3  2020-01-02   <1    4    7    2     1
2      4  2020-01-03   <1    5    7    1     1
3      5  2020-01-04   <1    4    8    2     1
4      6  2020-01-05    0    5    8    2     1

In [3]:
trend_df=data.drop('index', axis=1)
trend_df.head()

         Date CERB Mask Bike Zoom Patio
0  2020-01-01   <1    5    7    1     1
1  2020-01-02   <1    4    7    2     1
2  2020-01-03   <1    5    7    1     1
3  2020-01-04   <1    4    8    2     1
4  2020-01-05    0    5    8    2     1

In [4]:
trend_df['Date']=pd.to_datetime(trend_df['Date'], errors='coerce').copy()
trend_df['CERB'] = trend_df['CERB'].replace(
    {'<1': '0'})

In [5]:
trend_df['CERB']=trend_df['CERB'].astype('str', copy=True).astype('float', copy=True)
trend_df['Mask']=trend_df['Mask'].astype('str', copy=True).astype('float', copy=True)
trend_df['Bike']=trend_df['Bike'].astype('str', copy=True).astype('float', copy=True)
trend_df['Zoom']=trend_df['Zoom'].astype('str', copy=True).astype('float', copy=True)
trend_df['Patio']=trend_df['Patio'].astype('str', copy=True).astype('float', copy=True)

trend_df.dtypes

Date     datetime64[ns]
CERB            float64
Mask            float64
Bike            float64
Zoom            float64
Patio           float64
dtype: object

In [6]:
trend_df.head()

        Date  CERB  Mask  Bike  Zoom  Patio
0 2020-01-01   0.0   5.0   7.0   1.0    1.0
1 2020-01-02   0.0   4.0   7.0   2.0    1.0
2 2020-01-03   0.0   5.0   7.0   1.0    1.0
3 2020-01-04   0.0   4.0   8.0   2.0    1.0
4 2020-01-05   0.0   5.0   8.0   2.0    1.0

In [7]:
n_path="Resources/covid19.csv"

cdata = pd.read_csv(n_path) 
cdata.head()

,pruid,prname,prnameFR,date,numconf,numprob,numdeaths,numtotal,numtested,numrecover,...,percentdeath,numtestedtoday,numrecoveredtoday,percentactive,numactive,rateactive,numtotal_last14,ratetotal_last14,numdeaths_last14,ratedeaths_last14
0,35,Ontario,Ontario,31-01-2020,3,0,0.0,3,NaN,NaN,...,0.0,NaN,NaN,100.0,3.0,0.02,NaN,NaN,NaN,NaN
1,59,British Columbia,Colombie-Britannique,31-01-2020,1,0,0.0,1,NaN,NaN,...,0.0,NaN,NaN,100.0,1.0,0.02,NaN,NaN,NaN,NaN
2,1,Canada,Canada,31-01-2020,4,0,0.0,4,NaN,NaN,...,0.0,NaN,NaN,100.0,4.0,0.01,NaN,NaN,NaN,NaN
3,35,Ontario,Ontario,08-02-2020,3,0,0.0,3,NaN,NaN,...,0.0,NaN,NaN,100.0,3.0,0.02,NaN,NaN,NaN,NaN
4,59,British Columbia,Colombie-Britannique,08-02-2020,4,0,0.0,4,NaN,NaN,...,0.0,NaN,NaN,100.0,4.0,0.08,NaN,NaN,NaN,NaN

In [8]:
candata=cdata[[ 'date','prname','numconf','numdeaths','numdeathstoday','numtested','numtestedtoday','numrecover', 
     'numrecoveredtoday','numactive'
     ]]

In [9]:
candata["numdeaths"] = candata["numdeaths"].fillna(0).copy()
candata["numdeathstoday"] = candata["numdeathstoday"].fillna(0).copy()
candata["numtested"] = candata["numtested"].fillna(0).copy()
candata["numtestedtoday"] = candata["numtestedtoday"].fillna(0).copy()
candata["numrecover"] = candata["numrecover"].fillna(0).copy()
candata["numrecoveredtoday"] = candata["numrecoveredtoday"].fillna(0).copy()
candata["numactive"] = candata["numactive"].fillna(0).copy()

/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [10]:
candata.head()

,date,prname,numconf,numdeaths,numdeathstoday,numtested,numtestedtoday,numrecover,numrecoveredtoday,numactive
0,31-01-2020,Ontario,3,0.0,0.0,0.0,0.0,0.0,0.0,3.0
1,31-01-2020,British Columbia,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,31-01-2020,Canada,4,0.0,0.0,0.0,0.0,0.0,0.0,4.0
3,08-02-2020,Ontario,3,0.0,0.0,0.0,0.0,0.0,0.0,3.0
4,08-02-2020,British Columbia,4,0.0,0.0,0.0,0.0,0.0,0.0,4.0

/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

0.0      2037
1.0       184
2.0        98
3.0        72
4.0        39
         ...
142.0       1
178.0       1
71.0        1
65.0        1
137.0       1
Name: numdeathstoday, Length: 134, dtype: int64